### ISSUE TITLE
Can't get node-xz to build on Windows

### ISSUE THREAD

**Issue by manchicken** [robey/node-xz#8]
We've had a lot of trouble getting `node-xz` to build on Windows.

[npm-debug.log.zip](https://github.com/robey/node-xz/files/278049/npm-debug.log.zip)

```
C:\Work\hospitality-cloud-nodejs\cms\node_modules\xz>if not defined npm_config_node_gyp (node "C:\Users\Marc\AppData\Roaming\nvm\v5.1.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_xz_dep
  configure_and_make
  sh: ....depscd: command not found
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 127. [C:\Work\hospitality-cloud-nodejs\cms\node_modules\xz\build\deps\xz.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Marc \AppData\Roaming\nvm\v5.1.1\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Marc \\AppData\\Roaming\\nvm\\v5.1.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Work\hospitality-cloud-nodejs\cms\node_modules\xz
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Work\hospitality-cloud-nodejs\cms\node_modules\utf-8-validate\package.json'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! xz@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xz@1.2.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xz package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls xz
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Work\hospitality-cloud-nodejs\cms\npm-debug.log
```

**Comment by robey** [comment]
I don't have a Windows box, and probably never will, but if you can figure out how to make gyp work, I'll happily take the patch!

**Comment by dscalzi** [comment]
still an issue

**Comment by Esowteric** [comment]
Same error as @manchicken, on a Windows 10 machine, and I don't know enough to offer any solutions.

**Comment by bsholmes** [comment]
Same issue here. WIndows 7.

**Comment by Adobe-Android** [comment]
I'd use this repo now instead. https://www.npmjs.com/package/lzma-native
It's more up-to-date anyway. I have to get it to build on my Windows work machine and it's a hard requirement.

**Comment by robey** [comment]
I'm still willing to accept a patch if this is still happening in 2.0.

**Comment by TimeForANinja** [comment]
i can tell you that it's still happening...
since theres still is [no sh](https://github.com/robey/node-xz/blob/master/deps/xz.gyp#L43) in windows
since you don't seem to plan to add windows support - for those who need it - switching to lzma-native works perfect

**Comment by shikulja** [comment]
C:\Users\User>npm i xz

> xz@2.0.0 install C:\Users\User\node_modules\xz
> node-gyp rebuild


C:\Users\User\node_modules\xz>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "/m".
  unpack_xz_dep
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\Users\User\node_modules\xz\build\Release\\nothing.lib
  configure_and_make
  "sh" не является внутренней или внешней
  командой, исполняемой программой или пакетным файлом.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.tar gets(209,5): error MSB6006: "cmd.exe" завершилась с кодом 1. [C:\Users\User\node_modules\xz\build\deps\xz.vcxpr oj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\User\node_modules\xz
gyp ERR! node -v v11.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\User\package.json'
npm WARN User No description
npm WARN User No repository field.
npm WARN User No README data
npm WARN User No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xz@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xz@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by pvljz** [comment]
Hi,
please just update one line in `node-xz/deps/xz.gyp` from this:
`'action': [ 'sh', '-c', 'cd <(SHARED_INTERMEDIATE_DIR)/xz-<@(xz_version) && env CFLAGS="-fPIC" ./configure && make' ]`
to this:
`'action': ['cd <(SHARED_INTERMEDIATE_DIR)/xz-<@(xz_version) && env CFLAGS="-fPIC" ./configure && make' ]`
it does the same stuff. It's executed in current shell, on mac/linux via sh/bash, on windows via cmd.
thx

**Comment by robey** [comment]
that didn't quiiiite work, but poking around online revealed that adding an "eval" in front might help, so i just did that and pushed a new version. here's hoping! :)

**Comment by pvljz** [comment]
'eval' is not recognized as an internal or external command :-(

**Comment by chrisdmc** [comment]
**A Comprehensive Guide to Fixing Node-Gyp Issues on Windows**
May be helpful for some people:
https://spin.atomicobject.com/2019/03/27/node-gyp-windows/
